- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 7
  first_commit: 2019-05-30 10:22:56
- name: Diogo Pereira
  email: sir.suriv@gmail.com
  num_commits: 1
  first_commit: 2018-09-22 12:56:37
  github: diogocp
- name: Jens Nie
  email: jneines@web.de
  num_commits: 1
  first_commit: 2017-01-10 05:19:37
  github: jneines
- name: Willi Rath
  email: wrath@geomar.de
  num_commits: 1
  first_commit: 2017-04-05 12:18:52
  github: willirath
- name: Peter Parente
  email: ParenteP@valassis.com
  alternate_emails:
  - parente@cs.unc.edu
  num_commits: 15
  first_commit: 2016-12-12 13:21:44
  github: parente
- name: magnuhho
  email: 39699842+magnuhho@users.noreply.github.com
  num_commits: 2
  first_commit: 2018-10-25 06:43:07
  github: magnuhho
- name: Eric Dill
  email: thedizzle@gmail.com
  alternate_emails:
  - ericdill@users.noreply.github.com
  - eric.dill@maxpoint.com
  num_commits: 202
  first_commit: 2016-10-19 15:00:09
  github: ericdill
- name: Magnus Holm
  email: magnus.holm@usit.uio.no
  num_commits: 21
  first_commit: 2018-09-21 04:54:21
  github: magnuhho
- name: David Kent
  email: david.kent@bom.gov.au
  num_commits: 1
  first_commit: 2017-08-07 01:03:17
  github: dmkent
- name: Michael Peters
  email: mtpeters@us.ibm.com
  num_commits: 4
  first_commit: 2017-02-11 09:48:24
- name: John Kirkham
  email: kirkhamj@janelia.hhmi.org
  num_commits: 4
  first_commit: 2017-02-28 15:31:24
  github: jakirkham
- name: Johannes Haberl
  email: haberjha@schaeffler.com
  num_commits: 1
  first_commit: 2019-02-18 10:19:33
- name: Marius van Niekerk
  email: marius.v.niekerk@gmail.com
  num_commits: 1
  first_commit: 2016-12-14 22:38:47
  github: mariusvniekerk
- name: Bruno Oliveira
  email: nicoddemus@gmail.com
  num_commits: 1
  first_commit: 2017-03-04 13:16:22
  github: nicoddemus
- name: Max Point
  email: help@maxpoint.com
  github: maxpoint
  is_org: true
  num_commits: 0
  first_commit: 2019-10-22 14:25:24.612939
