language: python

python:
- 3.6
- 3.7

install:
- pip install -r requirements-test.txt
- pip install codecov
- pip install -e .

script:
- conda-mirror -h
- coverage run --concurrency=multiprocessing run_tests.py
- coverage combine
- coverage report -m
- flake8

after_success:
- codecov
